export const URL = 'http://localhost:9191/api/v1';

export const languages = [
  { label: 'Amharic', value: 'Amharic' },
  { label: 'Oromifa', value: 'Oromifa' },
  { label: 'Tigregna', value: 'Tigregna' },
  { label: 'Afar', value: 'Afar' },
  { label: 'Somali', value: 'Somali' },
  { label: 'Sidamo', value: 'Sidamo' },
  { label: 'Wolaytta', value: 'Wolaytta' },
  { label: 'Gurage', value: 'Gurage' },
  { label: 'Hadiya', value: 'Hadiya' },
  { label: 'English', value: 'English' },
  { label: 'Arabic', value: 'Arabic' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
  { label: 'Chinese', value: 'Chinese' },
  { label: 'Japanese', value: 'Japanese' },
  { label: 'Korean', value: 'Korean' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Portuguese', value: 'Portuguese' },
  { label: 'Russian', value: 'Russian' },
  { label: 'Italian', value: 'Italian' },
  { label: 'Turkish', value: 'Turkish' },
  { label: 'Dutch', value: 'Dutch' },
  { label: 'Swedish', value: 'Swedish' },
  { label: 'Norwegian', value: 'Norwegian' },
  { label: 'Danish', value: 'Danish' },
  { label: 'Polish', value: 'Polish' },
  { label: 'Greek', value: 'Greek' },
  { label: 'Thai', value: 'Thai' },
  { label: 'Vietnamese', value: 'Vietnamese' },
  { label: 'Bengali', value: 'Bengali' },
  { label: 'Urdu', value: 'Urdu' },
  { label: 'Persian', value: 'Persian' },
  { label: 'Hebrew', value: 'Hebrew' },
];
